---
title: "mnist numbers using clustering"
author: "Cesar A. Sanchez"
date: "6/27/2020"
output: html_document
---

```{r}
library(tidyverse)
library(dslabs)
#install.packages("dslabs")
# https://bradleyboehmke.github.io/HOML/kmeans.html
mnist <- dslabs::read_mnist()
```

```{r}
glimpse(mnist)
```

```{r}
features <- mnist$train$images
glimpse(features)
```
```{r}
str(features[1,])
d <- matrix(features[1,], nrow = 28, byrow = TRUE)
```

```{r}
library(reshape2)
digito<-melt(d)
#longData<-longData[longData$value!=0,]
digito
```

```{r}
ggplot(digito, aes(x = Var2, y = Var1)) +
  geom_raster(aes(fill=value))
```

```{r}
library(patchwork)
p <- function(i){
    d <- matrix(features[i,], nrow = 28, byrow = TRUE)
    digito<-melt(d)
    ggplot(digito, aes(x = Var2, y = Var1)) +
    geom_raster(aes(fill=value)) +  coord_fixed() + scale_y_reverse() +
    theme_void() + theme(legend.position = "none")
  }
```
```{r}
p(1) + p(2) + p(3) + p(4) + p(5) + p(6) + p(7) + p(8) + p(9)
```


Actividad ver la distribucion de pixeles para cada numero
```{r}
features <- mnist$train$images
labels_ <- mnist$train$labels
glimpse(features)
# str(features[1,])
# d <- matrix(features[1,], nrow = 28, byrow = TRUE)

numbers_dist = c(0,1,2,3,4,5,6,7,8,9)

numbers_df = data.frame(0,1,2,3,4,5,6,7,8,9)
df

for (i in 1:length(labels_)){
  if (labels_[i] in numbers_dist){
    
  }
    numbers_dist[labels_[i]] <- sort(features[i,], decreasing = FALSE)
}
glimpse(numbers_dist)
```

```{r}
count_words <- function(words){
  df <- data.frame(Word = words[1:length(words)])
  count(df, vars = "Word")
}

features <- mnist$train$images
labels_ <- mnist$train$labels
count_pixels <- function(features){
  df <- data.frame(Word = words[1:length(words)])
  count(df, vars = "Word")
}
```


```{r}
d %>%
  as.data.frame()
```

```{r}
mnist_clustering <- kmeans(features, centers = 10, nstart = 10)
str(mnist_clustering)
```

```{r}
# Extract cluster centers
mnist_centers <- mnist_clustering$centers
glimpse(mnist_centers)
```

```{r}
library(patchwork)
p <- function(i){
    cent <- matrix(mnist_centers[i,], nrow = 28, byrow = TRUE)
    digito<-melt(cent)
    ggplot(digito, aes(x = Var2, y = Var1)) +
    geom_raster(aes(fill=value)) +  coord_fixed() + scale_y_reverse() +
    theme_void() + theme(legend.position = "none")
  }
```

```{r}
p(1) + p(2) + p(3) + p(4) + p(5) + p(6) + p(7) + p(8) + p(9) + p(10)
```

```{r}
# Plot typical cluster digits
par(mfrow = c(2, 5), mar=c(0.5, 0.5, 0.5, 0.5))
layout(matrix(seq_len(nrow(mnist_centers)), 2, 5, byrow = FALSE))
for(i in seq_len(nrow(mnist_centers))) {
  image(matrix(mnist_centers[i, ], 28, 28)[, 28:1],xaxt="n", yaxt="n")
}
```

```{r}
# Create mode function
mode_fun <- function(x){  
  which.max(tabulate(x))
}

 

mnist_comparison <- data.frame(
  cluster = mnist_clustering$cluster,
  actual = mnist$train$labels
) %>%
  group_by(cluster) %>%
  mutate(mode = mode_fun(actual)) %>%
  ungroup() %>%
  mutate_all(factor, levels = 0:9)

 

# Create confusion matrix and plot results
yardstick::conf_mat(
  mnist_comparison, 
  truth = actual, 
  estimate = mode
) %>%
  autoplot(type = 'heatmap')
```

