---
title: "EDA"
author:"Cesar A. Sanchez"
output:html_document
  html_notebook: default
  word_document: default
---

```{r}
library(moderndive)
```
```{r}
?house_prices
```

```{r}
library(tidyverse)
library(ggplot2)
```

```{r}
view(house_prices)
glimpse(house_prices)
```

```{r}
p1 <- ggplot(house_prices, aes(x = price)) + geom_histogram(binwidth = 200000, color = 'white') + labs(x = 'price (USD)',title='House Price')
p1
```

```{r}
p2 <- ggplot(house_prices, aes(x = sqft_living)) + geom_histogram(binwidth = 500, fill='orange',color = 'white')+ labs(x = 'Living space (square food)',title='House size')
p2
```

```{r}
p3 <- ggplot(house_prices, aes(x = condition)) + geom_bar(aes(fill=condition))+ labs(x = 'condition',title='House condition') + theme(legend.position = 'none')
p3
```

```{r}
p1 + p2 + p3
```

# ejericio transformar p1 a pesos y p2 a metros cuadrados

```{r}
house_mod <- house_prices %>%
  mutate(price_pesos=price*21.50)
head(house_mod)
p1_new <- ggplot(house_mod, aes(x = price_pesos)) + geom_histogram(binwidth = 2000000, color = 'white') + labs(x = 'price (Pesos)',title='House Price')
p1_new
```

```{r}
house_mod <- house_prices %>%
  mutate(sqmts_living=sqft_living*0.092903)
head(house_mod)

p2_new <- ggplot(house_mod, aes(x = sqmts_living)) + geom_histogram(binwidth = 20, fill='orange',color = 'white')+ labs(x = 'Living space (square food)',title='House size')
p2_new
```

```{r}
house_prices %>%
  summarize(
    mean_price = mean(price),
    median_price = median(price),
    sd_price = sd(price),
    IQR_price = IQR(price)
  )
```

```{r}
house_prices %>%
  summarize(
    mean_mts_living = mean(sqft_living*0.092903),
    median_mts_living = median(sqft_living*0.092903),
    sd_mts_living = sd(sqft_living*0.092903),
    IQR_mts_living = IQR(sqft_living*0.092903)
  )

```

```{r}
house_prices_new <- house_prices %>%
  mutate(price_mxn = price*22) %>%
  mutate(log10_price = log10(price)) %>%
  mutate(log10_price_mxn = log10(price_mxn)) %>%
  mutate(log10_sqft_living = log10(sqft_living)) %>%
  mutate(mts_size = sqft_living*0.092903) %>%
  mutate(log10_mts_size = log10(sqft_living*0.092903))
glimpse(house_prices_new)
```

```{r}
# before
p_before <- ggplot(house_prices_new, aes(x = price)) + geom_histogram(binwidth = 200000, color = 'black', fill='yellow') + labs(x = 'price (USD)',title='House Price')

# after
p_after <- ggplot(house_prices_new, aes(x = log10_price)) + geom_histogram(bins = 40, color = 'black', fill='blue') + labs(x = 'log 10 price (USD)',title='House Price')
p_before
p_after
```

```{r}
# before
p_before_mts <- ggplot(house_prices_new, aes(x = mts_size)) + geom_histogram(bins = 40, color = 'black', fill='red') + labs(x = 'size (sqr mts)',title='House size')

# after
p_after_mts <- ggplot(house_prices_new, aes(x = log10_mts_size)) + geom_histogram(bins = 40, color = 'black', fill='orange') + labs(x = 'log 10 size (sqr mts)',title='House size')
p_before_mts
p_after_mts
```

# Modeling
```{r}
# ggplot(house_prices_new, aes(x = log10_size, y = log10_price, color = condition)) +
#  geom_point(alpha = 0.5, size = 0.5) +
#  labs(title = "House prices in Seattle") +
#  facet_wrap(~condition)
ggplot(house_prices_new, aes(x=log10_mts_size, y=log10_price_mxn, color = condition)) + geom_point(alpha = 0.2, size = 0.5) + labs(title = "house prices in Seattle") + facet_wrap(~condition) + geom_smooth(method ~ 'lm')
```

```{r}
price_prediction <- lm(log10_price_mxn ~ log10_mts_size * condition, data = house_prices_new)
parameters <- get_regression_table(price_prediction)
parameters
```

```{r}
params <- parameters$estimate
prediction <- function(params, size, indx) {
output <- if(indx == 1) params[1] + params[2] *log10(size) else (params[1] + params[1+indx]) +  (params[2] + params[5+indx]) *log10(size)
return(10^(output)) # going back to pesos
}
# predict by mts and condition
prediction(params, 100, 3)
```

